### ISSUE TITLE
Error when predicting with a previously trained model saved as ZIP

### ISSUE THREAD

**Issue by nunopimpaomartins** [juglab/N2V_fiji#11]
Hello!

When I try using a previously trained model to denoise an image, I have the following error.

[ERROR] Module threw exception
java.lang.NullPointerException: entry
	at java.util.zip.ZipFile.getInputStream(ZipFile.java:361)
	at de.csbdresden.n2v.train.ModelSpecification.extractFile(ModelSpecification.java:235)
	at de.csbdresden.n2v.train.ModelSpecification._readConfig(ModelSpecification.java:205)
	at de.csbdresden.n2v.train.ModelSpecification.readConfig(ModelSpecification.java:194)
	at de.csbdresden.n2v.predict.N2VPrediction.setModelFile(N2VPrediction.java:48)
	at de.csbdresden.n2v.command.N2VPredictCommand.run(N2VPredictCommand.java:58)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

![n2v_predict_error_log](https://user-images.githubusercontent.com/16762812/75675368-52efa980-5c87-11ea-950b-e2b9b3b7574f.jpg)

![n2v_predict_error](https://user-images.githubusercontent.com/16762812/75675395-61d65c00-5c87-11ea-9f9d-ac4a86d5b5a1.png)

If I load it through `CSBDeep > Run your IsoNet`, it works fine.

The model was generated by training N2V through a Jupyter notebook.

TF1.13.1
CUDA 10.0
cuDNN 7.4

Cheers,
Nuno

**Comment by frauzufall** [comment]
Uhm, yes, I see how this is confusing... 

For N2V during training the normalization parameters are calculated and exported (`mean` and `stdDev` of training data). They have to be used for normalization during prediction as well.

If you train N2V in Fiji, it adds a `n2v.model.yaml` to the ZIP with the normalization parameters in it. You can run prediction on these models and it will use the normalization parameters from the ZIP.

N2V in python does not export the same format yet. You can run it in Fiji using the `CSBDeep > Run your network` command (not the IsoNet, that does preprocessing specific to the CARE IsoNet architecture). You have to disable normalization in the `Run your network` command, because that's percentile normalization and not the one from N2V, and do normalization yourself before running the plugin.

This definitely needs improvement... @tibuch we need to export a similar YAML file in python (compatible to the model zoo)

**Comment by frauzufall** [comment]
With the current version running an exported model from python should work now.
