### ISSUE TITLE
N2V Fiji crashes

### ISSUE THREAD

**Issue by Eddymorphling** [juglab/N2V_fiji#31]
The N2V Fiji plugin recently stopped working after the latest release of Fiji updates. It was working well in the past on my NVIDIA GPU and TF in Fiji. I also created a post about this on the ImageJ forum ([link](https://forum.image.sc/t/noise2void-error-after-fiji-update/83871)). The error message I get is below. Any clue what could be causing the issue?
```

java.lang.IllegalStateException: Generated message class "org.tensorflow.framework.TensorInfo" missing method "hasName".
	at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1998)
	at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.<init>(GeneratedMessageV3.java:2351)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessageV3.java:2418)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularStringFieldAccessor.<init>(GeneratedMessageV3.java:3071)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:2137)
	at org.tensorflow.framework.TensorInfo.internalGetFieldAccessorTable(TensorInfo.java:130)
	at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:139)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:363)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:353)
	at com.google.protobuf.TextFormat$Printer.printToString(TextFormat.java:615)
	at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:110)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at java.util.AbstractMap.toString(AbstractMap.java:559)
	at com.google.protobuf.MapField$MutabilityAwareMap.toString(MapField.java:372)
	at java.util.Collections$UnmodifiableMap.toString(Collections.java:1495)
	at net.imagej.modelzoo.consumer.model.tensorflow.TensorFlowModel.loadSignature(TensorFlowModel.java:164)
	at net.imagej.modelzoo.consumer.model.tensorflow.TensorFlowModel.loadModel(TensorFlowModel.java:154)
	at net.imagej.modelzoo.DefaultModelZooArchive.createModelInstance(DefaultModelZooArchive.java:119)
	at net.imagej.modelzoo.consumer.AbstractModelZooPrediction.loadModel(AbstractModelZooPrediction.java:156)
	at net.imagej.modelzoo.consumer.AbstractModelZooPrediction.run(AbstractModelZooPrediction.java:99)
	at net.imagej.modelzoo.consumer.command.AbstractSingleImagePredictionCommand.run(AbstractSingleImagePredictionCommand.java:101)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NoSuchMethodException: org.tensorflow.framework.TensorInfo.hasName()
	at java.lang.Class.getMethod(Class.java:1786)
	at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1995)
	... 31 more
[INFO] ModelZoo prediction exit (took 37 milliseconds)
[INFO] Using native TensorFlow version: TF 1.15.0 GPU (CUDA 10.0, CuDNN >= 7.4.1)
[INFO] Loading TensorFlow model unnamed_n2v_lowest_loss_1689638947759 from source file file:/C:/Users/praveen/AppData/Local/Temp/tf_saved_model_bundle4781063617951810542.zip
```

Thanks a bunch!

**Comment by jdeschamps** [comment]
Could you click on the "31 more" and paste what's hidden? That is the trace of the error and it might indicate where the problem originates from. Hopefully that can help solve the problem.

Know that this plugin is unfortunately not maintained anymore. These days we advise using the Python napari plugin (https://github.com/juglab/napari-n2v).

**Comment by Eddymorphling** [comment]
Hi unfortunately, I am unable to get the rest of the lines on the error code :( Fiji does not allow me to expand it. I have also tried napari-n2v but I haven't been successful to use GPU/CUDA yet but I was able to on Fiji. Hence I have been using it on Fiji so far.

**Comment by jdeschamps** [comment]
Alright! What system do you have?
- OS
- GPU model
- CUDA version

Have you tried TF 1.12 rather than 1.15? Sometimes this made the trick (mostly with macOS though...). 

You can also open a ticket here to get help on setting up the Python version: https://github.com/juglab/napari-n2v

Please note that this is holiday season, so we will not be able to help much until August :/

**Comment by Eddymorphling** [comment]
Thanks for reaching out, I understand its holiday season which your team fully deserves for maintaining these awesome plugins! 

I am running on Win11, an Nvidia QuadroP5000, using TF 1.15 which I believe is comes prebuilt with CUDA 10.0 and cuDNN=7.4. I tried TF 1.15, 1.14 but not TF 1.12. Will try that and report back. 

Thanks. 

**EDIT**: Reporting back. Same error with TF 1.12 GPU

**Comment by purviljani** [comment]
I was facing a similar issue with predicting using CSBDeep denoiseg. The following worked for me: Help -> Update -> Manage Update Sites -> Check TensorFlow -> Apply and Close -> Apply Changes -> Restart ImageJ

**Comment by Eddymorphling** [comment]
> I was facing a similar issue with predicting using CSBDeep denoiseg. The following worked for me: Help -> Update -> Manage Update Sites -> Check TensorFlow -> Apply and Close -> Apply Changes -> Restart ImageJ

Which TF version does it work on?

**Comment by purviljani** [comment]
I have tried it on 1.12.0 CPU, 1.15.0 CPU and 1.15.0 GPU (CUDA 10.0, CuDNN >=7.4.1). Works on all of them for me.

**Comment by Eddymorphling** [comment]
Thanks! Strangely that did not work for me :(

**Comment by jdeschamps** [comment]
Hey, sorry for the delay.

Have you tried [Praveen's trick here](https://forum.image.sc/t/noise2void-for-fiji-windows-gpu-support/34907/44) ? One of "adding the PATH" or copying the .dll might work for you as well!

**Comment by Eddymorphling** [comment]
> Hey, sorry for the delay.
> 
> Have you tried [Praveen's trick here](https://forum.image.sc/t/noise2void-for-fiji-windows-gpu-support/34907/44) ? One of "adding the PATH" or copying the .dll might work for you as well!

Hi! I would have to say indeed I have because I am Praveen :)

**Comment by jdeschamps** [comment]
Gad damn it... Hi Praveen. :)

- Do you have access to a "non-updated" Fiji version? (I imagine not)
- Have you tried downloading an [earlier Fiji](https://downloads.imagej.net/fiji/archive/)?
- If you go "Window > Update", then click on "Advanced mode", can you write down the versions for the following items (search for them, click on them and in "details" there should be versions):
   - imagej-modelzoo.jar
   - n2v.jar
   - csbdeep.jar
   - imagej-tensorflow.jar
   - libtensorflow.jar
   - libtensorflow_jni.jar
   - tensorflow.jar

I am honestly quite confused because the error looks like incompatible package versions, but none of these artefacts have been updated in a long time as far as I know.

**Comment by martin-held-hereon** [comment]
> I was facing a similar issue with predicting using CSBDeep denoiseg. The following worked for me: Help -> Update -> Manage Update Sites -> Check TensorFlow -> Apply and Close -> Apply Changes -> Restart ImageJ

I had the same isssue and adding TensorFlow to the update sites worked for me! Thanks to everyone being active and helpful around N2V!

**Comment by Eddymorphling** [comment]
Update - I was able to get it working. I just redownloaded Fiji and tried with the update sites CSBDeep and Tensorflow. Thanks for all the help! Will try to setup it up on Python now as @jdeschamps  suggested 👍

**Comment by jdeschamps** [comment]
Happy it worked out, thanks @martin-held-hereon for the input!

@Eddymorphling let us know in the napari-n2v repo if you encounter any problem. This is really important to us to remove any barrier preventing user from using these tools. :)

**Comment by Eddymorphling** [comment]
Think I have the n2v repo working too now. For some weird reason in the past, I could not get n2v to use GPU and TF in the conda env I created. Think it might be related to a CUDA/TF mismatch. But a fresh env with TF v10.1 and CUDA 11 and cuDNN 8.2 seems to have fixed it. Thank you.

**Comment by joaomamede** [comment]
I have this problem with freshly downloaded Fiji and after adding CSBdeep + Tensorflow to the update sites.

```
[INFO] ModelZoo sanity check start
[INFO] Using native TensorFlow version: TF 1.15.0 GPU (CUDA 10.0, CuDNN >= 7.4.1)
[INFO] Loading TensorFlow model Noise2Void_-_ERT_GFP_1698207970574 from source file file:/home/jmamede/Area51/fsu/n2v_ERT_GFP/bioimage.io.zip
[INFO] Caching TensorFlow models to /home/jmamede/Area51/fsu/Fiji.app/models
[INFO] Unpacking meta.json
[INFO] Unpacking model.yaml
[INFO] Unpacking saved_model.pb
[INFO] Unpacking testinput.tif
[INFO] Unpacking testoutput.tif
[INFO] Unpacking variables/
[INFO] Unpacking variables/variables.index
[INFO] Unpacking variables/variables.data-00000-of-00001
java.lang.IllegalArgumentException: NodeDef mentions attr 'allowed_devices' not in Op<name=VarHandleOp; signature= -> resource:resource; attr=container:string,default=""; attr=shared_name:string,default=""; attr=dtype:type; attr=shape:shape; is_stateful=true>; NodeDef: {{node batch_normalization_5/moving_mean}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[batch_normalization_5/moving_mean]]
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.access$000(SavedModelBundle.java:27)
	at org.tensorflow.SavedModelBundle$Loader.load(SavedModelBundle.java:32)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:95)
	at net.imagej.tensorflow.CachedModelBundle.<init>(CachedModelBundle.java:44)
	at net.imagej.tensorflow.DefaultTensorFlowService.loadCachedModel(DefaultTensorFlowService.java:135)
	at net.imagej.modelzoo.consumer.model.tensorflow.TensorFlowModel.loadModelFile(TensorFlowModel.java:172)
	at net.imagej.modelzoo.consumer.model.tensorflow.TensorFlowModel.loadModel(TensorFlowModel.java:153)
	at net.imagej.modelzoo.DefaultModelZooArchive.createModelInstance(DefaultModelZooArchive.java:119)
	at net.imagej.modelzoo.consumer.AbstractModelZooPrediction.loadModel(AbstractModelZooPrediction.java:156)
	at net.imagej.modelzoo.consumer.AbstractModelZooPrediction.run(AbstractModelZooPrediction.java:99)
	at net.imagej.modelzoo.consumer.command.AbstractSingleImagePredictionCommand.run(AbstractSingleImagePredictionCommand.java:101)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

This only happens if I use a my python trained models. If I use the DEMO models in the plugin it works fine. I tried unzipping and zipping and the problem persists.
Here's my model file (post unzipping and zipping again)

[bioimage.io.zip](https://github.com/juglab/N2V_fiji/files/13161358/bioimage.io.zip)

Napari plugin in the same machine works fine.

With the DEMO models from the Plugins->CSBDEEP->N2V:
```
[INFO] Using native TensorFlow version: TF 1.15.0 GPU (CUDA 10.0, CuDNN >= 7.4.1)
[INFO] Loading TensorFlow model GenericNetwork_model-tribolium_2019-01-10-04-34-37 from source file http://csbdeep.bioimagecomputing.com/model-tribolium.zip
[INFO] Unpacking variables/
[INFO] Unpacking variables/variables.data-00000-of-00001
[INFO] Unpacking variables/variables.index
[INFO] Unpacking saved_model.pb
[INFO] Shape of input tensor: [-1, -1, -1, -1, 1]
[INFO] Shape of output tensor: [-1, -1, -1, -1, 2]
[INFO] Normalize .. 
[INFO] Dataset type: 32-bit signed float, converting to FloatType.
[INFO] Dataset dimensions: [1020, 1020]
[INFO] INPUT NODE: 
[INFO] Mapping of tensor input: 
[INFO]    datasetAxes:[X, Y]
[INFO]    nodeAxes:[(Time, -1), (Z, -1), (Y, -1), (X, -1), (Channel, 1)]
[INFO]    mapping:[2, 3, 1, 0, 4]
[INFO] OUTPUT NODE: 
[INFO] Mapping of tensor output: 
[INFO]    datasetAxes:[X, Y]
[INFO]    nodeAxes:[(Time, -1), (Z, -1), (Y, -1), (X, -1), (Channel, 2)]
[INFO]    mapping:[2, 3, 1, 0, 4]
[INFO] Complete input axes: [X, Y, Time, Z, Channel]
[INFO] Tiling actions: [TILE_WITH_PADDING, TILE_WITH_PADDING, TILE_WITHOUT_PADDING, TILE_WITH_PADDING, NO_TILING]
[INFO] Dividing image into 9 tile(s)..
[INFO] Size of single image tile: [344, 344, 1, 8, 1]
[INFO] Final image tiling: [3, 3, 1, 1, 1]
[INFO] Network input size: [408, 408, 1, 8, 1]
[INFO] Processing tile 1..
[INFO] Processing tile 2..
[INFO] Processing tile 3..
[INFO] Processing tile 4..
[INFO] Processing tile 5..
[INFO] Processing tile 6..
[INFO] Processing tile 7..
[INFO] Processing tile 8..
[INFO] Processing tile 9..
[INFO] Network output size: [408, 408, 1, 8, 2]
[INFO] POSTPROCESSING
[INFO] Output axes: [X, Y, Time, Z, Channel]
[INFO] Merging tiles..
[INFO] Crop to original size..
[INFO] Output axes: [X, Y, Time, Z, Channel]
[INFO] Displaying result image..
[INFO] img dim before wrapping into dataset: [1020, 1020, 2]
[INFO] CSBDeep plugin exit (took 25994 milliseconds)
```

**Comment by jdeschamps** [comment]
This is issue is currently closed and relates to a problem different from yours.

Could you open [a new issue](https://github.com/juglab/N2V_fiji/issues/new) with this problem? And can you give more details about how to you got the network?

Then we will try to see what's happening!

Thanks!
